version: 2

jobs:
  build_and_push_tag:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker build -t ictu/appstore:${CIRCLE_TAG} .
            MAJOR_VERSION=${CIRCLE_TAG/.*}; docker tag ictu/appstore:${CIRCLE_TAG} ictu/appstore:${MAJOR_VERSION}
            MINOR_VERSION=${CIRCLE_TAG%.*}; docker tag ictu/appstore:${CIRCLE_TAG} ictu/appstore:${MINOR_VERSION}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/appstore:${CIRCLE_TAG}
            docker push ictu/appstore:${MINOR_VERSION}
            docker push ictu/appstore:${MAJOR_VERSION}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_tag:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/